name: Python Linting

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'  # Using 3.9 for stable linting tools support
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # Install the package in dev mode to ensure imports work correctly
        python -m pip install -e .
        # Install specific versions of linting tools
        python -m pip install black==23.1.0 isort==5.12.0
    
    - name: Check formatting with black
      run: |
        # Run with less strict options for backward compatibility
        black --check --diff --skip-string-normalization antinature tests
    
    - name: Check imports with isort
      run: |
        # Run with more permissive settings
        isort --check --diff --profile black antinature tests 